language: objective-c
osx_image: xcode10
script:
    - xcodebuild clean test -project modcalculator.xcodeproj -scheme modcalculator -destination "platform=iOS Simulator,OS=12.2,name=iPhone XS Max" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
after_success:
  - bash <(curl -s https://codecov.io/bash) -t uuid-aec4d588-6959-40b7-951b-c934507e1d36
